version: '3.4'

services:

  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    # environment:
    #   SIGNUPS_ALLOWED: 'false'
    #   ADMIN_TOKEN: 'your authentication token'
    ports:
      - '127.0.0.1:8080:80'
    volumes:
      - vw-data:/data/
       
  backup:
    image: aSouchereau/docker-vaultwarden-backup:latest
    restart: always
    volumes:
      - vw-data:/bitwarden/data/
    #   - /path/to/env:/.env

volumes:
  vw-data:
    # Specify the name of the volume where you save the vaultwarden data,
    name: vw-data