version: '3.4'

services:

  vaultwarden:
    image: vaultwarden/server:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - vw-data:/data/
       
  backup:
    image: asouchereau/vaultwarden-backup-gfs:latest
    restart: always
    volumes:
      - vw-data:/vaultwarden/data/
      - vw-backups:/app/output
    environment:
      - DAILY_RETENTION=7
      - WEEKLY_RETENTION=8
      - MONTHLY_RETENTION=6

volumes:
  vw-data:
    # This volume is shared between the vaultwarden and backup containers
    name: vw-data
  vw-backups:
    # This volume is used to store your archive files
    name: vw-backups